# Generated by Django 5.2.6 on 2025-09-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='payment_method',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
